# model options
model:  <Transformer/TransMIL/AttentionMIL/Transformer_gpt_random/Transformer_gpt_random_4_quantile...>
model_config:
  depth: 6
  heads: 6
  dim_head: 64
  dim: 384
  mlp_dim: 384
  dropout: 0
norm: <normalizatio_used>
feats: <feature_extractor_used>
input_dim: <feature_dim>